import { DurableObject } from "cloudflare:workers";
export default { async fetch(request, env) { const url=new URL(request.url); if(url.pathname==="/ws"){if(request.headers.get("Upgrade")!=="websocket") return new Response("WebSocket required",{status:426}); const id=env.CHAT_HUB.idFromName("main"); return env.CHAT_HUB.get(id).fetch(request);} if(url.pathname==="/health") return Response.json({ok:true,service:"webchat",version:2}); return env.ASSETS.fetch(request); } };
export class ChatHub extends DurableObject {
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;this.chats=new Map();}
 async fetch(request){const url=new URL(request.url);const pair=new WebSocketPair();const [client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({role:"unknown",chatId:url.searchParams.get("chat")||"",name:""});return new Response(null,{status:101,webSocket:client});}
 broadcast(data,p=()=>true){const msg=JSON.stringify(data);for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment()||{};if(p(a,ws))try{ws.send(msg)}catch{}}}
 webSocketMessage(ws,raw){let d;try{d=JSON.parse(raw)}catch{return}const cur=ws.deserializeAttachment()||{};
  if(d.type==="join"){const role=d.role==="owner"?"owner":"visitor",chatId=String(d.chatId||crypto.randomUUID()),name=String(d.name||"Pengunjung").trim().slice(0,40);
   if(role==="owner"){const supplied=String(d.ownerKey||""),expected=String(this.env.OWNER_KEY||"");if(!expected||supplied!==expected){ws.send(JSON.stringify({type:"auth_error",message:"OWNER_KEY salah atau belum diatur di Cloudflare."}));try{ws.close(1008,"Unauthorized")}catch{}return}ws.serializeAttachment({role:"owner",chatId:"",name:"Owner"});for(const x of this.chats.values())ws.send(JSON.stringify({type:"chat_available",...x}));ws.send(JSON.stringify({type:"owner_ready"}));return;}
   this.chats.set(chatId,{chatId,name,online:true,updated:Date.now()});ws.serializeAttachment({role:"visitor",chatId,name});ws.send(JSON.stringify({type:"joined",chatId,name}));this.broadcast({type:"chat_new",chatId,name,online:true},a=>a.role==="owner");return;}
  if(cur.role==="visitor"&&d.type==="message"){const text=String(d.text||"").trim().slice(0,2000);if(!text)return;this.chats.set(cur.chatId,{...(this.chats.get(cur.chatId)||{}),chatId:cur.chatId,name:cur.name,online:true,updated:Date.now()});this.broadcast({type:"message",chatId:cur.chatId,sender:"visitor",name:cur.name||"Pengunjung",text,time:new Date().toISOString()},a=>a.role==="owner"||(a.role==="visitor"&&a.chatId===cur.chatId));return;}
  if(cur.role==="owner"&&d.type==="message"){const chatId=String(d.chatId||"").trim(),text=String(d.text||"").trim().slice(0,2000);if(!chatId||!text)return;this.broadcast({type:"message",chatId,sender:"owner",name:"Owner",text,time:new Date().toISOString()},a=>(a.role==="visitor"&&a.chatId===chatId)||a.role==="owner");}
 }
 webSocketClose(ws){const a=ws.deserializeAttachment()||{};if(a.role==="visitor"&&a.chatId){const c=this.chats.get(a.chatId);if(c){c.online=false;c.updated=Date.now();this.chats.set(a.chatId,c);this.broadcast({type:"chat_status",chatId:a.chatId,name:a.name,online:false},x=>x.role==="owner")}}}
 webSocketError(ws){this.webSocketClose(ws)}
}
